[pytest]
;设置pytest命令行参数，无需每次执行输入
addopts = -vs --alluredir=./allure-results --clean-alluredir

;搜索用例的目录
testpaths =

;搜索的用例模块名，支持通配符
python_files = test*.py

;搜索测试的类名，指定测试某一个类
python_classes = Test*

;搜索测试的方法名<具体的函数/用例>
python_functions = test_*